// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("BioFSharp.ImgP")>]
[<assembly: AssemblyProductAttribute("BioFSharp")>]
[<assembly: AssemblyDescriptionAttribute("An open source bioinformatics toolbox written in F#. <https://csbiology.github.io/BioFSharp/>")>]
[<assembly: AssemblyVersionAttribute("0.0.12")>]
[<assembly: AssemblyFileVersionAttribute("0.0.12")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "BioFSharp.ImgP"
    let [<Literal>] AssemblyProduct = "BioFSharp"
    let [<Literal>] AssemblyDescription = "An open source bioinformatics toolbox written in F#. <https://csbiology.github.io/BioFSharp/>"
    let [<Literal>] AssemblyVersion = "0.0.12"
    let [<Literal>] AssemblyFileVersion = "0.0.12"
    let [<Literal>] AssemblyConfiguration = "Release"
