
(*** hide ***)
// This block of code is omitted in the generated HTML documentation. Use 
// it to define helpers that you do not want to show in the documentation.
#I @"../../bin/BioFSharp/net47/"
#I @"../../bin/BioFSharp.BioDB/net45/"
#I @"../../bin/BioFSharp.ImgP/net47"
#I @"../../bin/BioFSharp.IO/net47/"
#I @"../../bin/BioFSharp.Parallel/net47/"
#I @"../../bin/BioFSharp.Stats/net47/"
#I @"../../bin/BioFSharp.Vis/net47/"
#r @"../../lib/Formatting/FSharp.Plotly.dll"
#r "BioFSharp.dll"
#r "BioFSharp.IO.dll"
#r "FSharpAux.dll"
#r "FSharpAux.IO.dll"

let formatExample = """
CLUSTAL O(1.2.4) multiple sequence alignment





C_reinhardtii      MVPQTETKAGAGFKAGVKDYRLTYYTPDYVVRDTDILAAFRMTPQLGVPPEECGAAVAAE

N_tabacum          MSPQTETKASVGFKAGVKEYKLTYYTPEYQTKDTDILAAFRVTPQPGVPPEEAGAAVAAE

A_thaliana         MSPQTETKASVGFKAGVKEYKLTYYTPEYETKDTDILAAFRVTPQPGVPPEEAGAAVAAE

O_sativa           MSPQTETKASVGFKAGVKDYKLTYYTPEYETKDTDILAAFRVTPQPGVPPEEAGAAVAAE

                   * *******..*******:*:******:* .:*********:*** ******.*******



C_reinhardtii      SSTGTWTTVWTDGLTSLDRYKGRCYDIEPVPGEDNQYIAYVAYPIDLFEEGSVTNMFTSI

N_tabacum          SSTGTWTTVWTDGLTSLDRYKGRCYRIERVVGEKDQYIAYVAYPLDLFEEGSVTNMFTSI

A_thaliana         SSTGTWTTVWTDGLTSLDRYKGRCYHIEPVPGEETQFIAYVAYPLDLFEEGSVTNMFTSI

O_sativa           SSTGTWTTVWTDGLTSLDRYKGRCYHIEPVVGEDNQYIAYVAYPLDLFEEGSVTNMFTSI

                   ************************* ** * **. *:*******:***************



C_reinhardtii      VGNVFGFKALRALRLEDLRIPPAYVKTFVGPPHGIQVERDKLNKYGRGLLGCTIKPKLGL

N_tabacum          VGNVFGFKALRALRLEDLRIPPAYVKTFQGPPHGIQVERDKLNKYGRPLLGCTIKPKLGL

A_thaliana         VGNVFGFKALAALRLEDLRIPPAYTKTFQGPPHGIQVERDKLNKYGRPLLGCTIKPKLGL

O_sativa           VGNVFGFKALRALRLEDLRIPPTYSKTFQGPPHGIQVERDKLNKYGRPLLGCTIKPKLGL

                   ********** ***********:* *** ****************** ************



C_reinhardtii      SAKNYGRAVYECLRGGLDFTKDDENVNSQPFMRWRDRFLFVAEAIYKAQAETGEVKGHYL

N_tabacum          SAKNYGRAVYECLRGGLDFTKDDENVNSQPF-RWRDRFLFCAEALYKAQAETGEIKGHYL

A_thaliana         SAKNYGRAVYECLRGGLDFTKDDENVNSQPFMRWRDRFLFCAEAIYKSQAETGEIKGHYL

O_sativa           SAKNYGRACYECLRGGLDFTKDDENVNSQPFMRWRDRFVFCAEAIYKSQAETGEIKGHYL

                   ******** ********************** ******:* ***:**:******:*****



C_reinhardtii      NATAGTCEEMMKRAVCAKELGVPIIMHDYLTGGFTANTSLAIYCRDNGLLLHIHRAMHAV

N_tabacum          NATAGTCEEMIKRAVFARELGVPIVMHDYLTGGFTANTSLAHYCRDNGLLLHIHRAMHAV

A_thaliana         NATAGTCEEMIKRAVFARELGVPIVMHDYLTGGFTANTSLSHYCRDNGLLLHIHRAMHAV

O_sativa           NATAGTCEEMIKRAVFARELGVPIVMHDYLTGGFTANTSLAHYCRDNGLLLHIHRAMHAV

                   **********:**** *:******:***************: ******************



C_reinhardtii      IDRQRNHGIHFRVLAKALRMSGGDHLHSGTVVGKLEGEREVTLGFVDLMRDDYVEKDRSR

N_tabacum          IDRQKNHGIHFRVLAKALRMSGGDHIHSGTVVGKLEGERDITLGFVDLLRDDFVEQDRSR

A_thaliana         IDRQKNHGMHFRVLAKALRLSGGDHIHAGTVVGKLEGDRESTLGFVDLLRDDYVEKDRSR

O_sativa           IDRQKNHGMHFRVLAKALRMSGGDHIHAGTVVGKLEGEREMTLGFVDLLRDDFIEKDRAR

                   ****:***:**********:*****:*:*********:*: *******:***::*:**:*



C_reinhardtii      GIYFTQDWCSMPGVMPVASGGIHVWHMPALVEIFGDDACLQFGGGTLGHPWGNAPGAAAN

N_tabacum          GIYFTQDWVSLPGVLPVASGGIHVWHMPALTEIFGDDSVLQFGGGTLGHPWGNAPGAVAN

A_thaliana         GIFFTQDWVSLPGVLPVASGGIHVWHMPALTEIFGDDSVLQFGGGTLGHPWGNAPGAVAN

O_sativa           GIFFTQDWVSMPGVIPVASGGIHVWHMPALTEIFGDDSVLQFGGGTLGHPWGNAPGAAAN

                   **:***** *:***:***************.******: ******************.**



C_reinhardtii      RVALEACTQARNEGRDLAREGGDVIRSACKWSPELAAACEVWKEIKFEFDTIDKL----

N_tabacum          RVALEACVKARNEGRDLAQEGNEIIREACKWSPELAAACEVWKEIVFNFAAVDVLDK--

A_thaliana         RVALEACVQARNEGRDLAVEGNEIIREACKWSPELAAACEVWKEITFNFPTIDKLDGQE

O_sativa           RVALEACVQARNEGRDLAREGNEIIRSACKWSPELAAACEIWKAIKFEFEPVDKLDS--

                   *******.:********* **.::**.*************:** * *:*  :* *    
"""
(**
<table class="HeadAPI">
<td class="Head"><h1>Clustal format</h1></td>
<td class="API">
    <a id="APILink" href="https://csbiology.github.io/BioFSharp/reference/biofsharp-io-clustal.html" >&#128194;View module documentation</a>
</td>
</table>

The clustal file format is the standard output format of alignments generated by clustal algorithms (Clustal W, Clustal Omega...). Usually the first line is a one line header, including the clustal version and possibly other information. This is followed by at least one empty line.  
Afterwards there are blocks of sequence data. The amount of blocks depends on the length of the sequences. Every line in those blocks consists of: 
    
1. Name of Sequence  
2. White space  
3. Up to 60 characters of the sequence, where `-` denotes gaps  
4. (not necessarily) white space and a number stating the cumulative amount of non gap characters of the given sequence up to this point  

The last line of every block is a sequence of symbols denoting the degree of conservation for this column. (`*` = identical residues, `:` = conserved substitution, `.` = semi-conserved substitutions, ` ` = no match)  

Blocks are separated by at least one empty line.  
  
As an example, the peptide sequences of the large chain subunit of RuBisCO of different organisms was aligned with Clustal Omega:  
<br>
<button type="button" class="btn" data-toggle="collapse" data-target="#clustalExample">Show/Hide example</button>
<div id="clustalExample" class="collapse clustalExample ">

*)

(*** include-value:formatExample ***)

(**

<button type="button" class="btn" data-toggle="collapse" data-target="#clustalExample">Hide again</button>  
</div>


## Reading Clustal files

To read Clustal files, just use the ofFile function located in the Clustal module of the BioFSharp.IO namespace. It does not need anything but the file path and will return the alignment as `Alignment`.  
Keep in mind that if your clustal file containts numbers representing the character count at the line end. They and their line space will be included in the Alignment. Make sure to filter them out if not needed.

*)

open BioFSharp.IO

let fileDir = __SOURCE_DIRECTORY__ + "/data/"

let path = fileDir + "clustalExample.asn"

let clustalAlignment = Clustal.ofFile path

(*** include-value: clustalAlignment ***)

(**

## Writing Clustal files

For writing clustal files you can use the `toFile` function. It takes a path and the alignment. The type of alignment is the same as the result of the reading function. You can see this above.

*)
let outputPath = fileDir + "clustalOutputExample.asn"

(*** do-not-eval ***)
Clustal.toFileWithOverWrite outputPath clustalAlignment