// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("BioFSharp.Parallel")>]
[<assembly: AssemblyProductAttribute("BioFSharp")>]
[<assembly: AssemblyDescriptionAttribute("An open source bioinformatics toolbox written in F#. <https://csbiology.github.io/BioFSharp/>")>]
[<assembly: AssemblyVersionAttribute("1.0.02")>]
[<assembly: AssemblyFileVersionAttribute("1.0.02")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "BioFSharp.Parallel"
    let [<Literal>] AssemblyProduct = "BioFSharp"
    let [<Literal>] AssemblyDescription = "An open source bioinformatics toolbox written in F#. <https://csbiology.github.io/BioFSharp/>"
    let [<Literal>] AssemblyVersion = "1.0.02"
    let [<Literal>] AssemblyFileVersion = "1.0.02"
    let [<Literal>] AssemblyConfiguration = "Release"
