// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("BioFSharp")>]
[<assembly: AssemblyProductAttribute("BioFSharp")>]
[<assembly: AssemblyDescriptionAttribute("BioFSharp aims to be a user-friendly library for Bioinformatics written in F# as the official successor of FSharpBio.")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "BioFSharp"
    let [<Literal>] AssemblyProduct = "BioFSharp"
    let [<Literal>] AssemblyDescription = "BioFSharp aims to be a user-friendly library for Bioinformatics written in F# as the official successor of FSharpBio."
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
